* Tasks
  Understand Weka's /filters/, which act as pre-processing activities.
  * Using multiple filters to transform datasets.
  * Embed filters within classification models.
** Removing Attributes
   Possible non-interesting histograms:
   * other_parties
   * foreign_worker
*** Naive-Bayes
    | Correctly Classified Instances   | 755 (75.5%) |
    | Incorrectly Classified Instances | 245 (24.5%) |
    | Kappa statistic                  |      0.3844 |
    | Mean absolute error              |      0.2959 |
    | Root mean squared error          |      0.4216 |
    | Relative absolute error          |    70.4246% |
    | Root relative squared error      |    91.9982% |
    | Total Number of Instances        |        1000 |
**** Re-evaluted on data
     Classifiers wrapped in InputMappedClassifier
     | Correctly Classified Instances   | 770 (77%) |
     | Incorrectly Classified Instances | 230 (23%) |
     | Kappa statistic                  |    0.4261 |
     | Mean absolute error              |    0.2851 |
     | Root mean squared error          |    0.4102 |
     | Total Number of Instances        |      1000 |
***** Warning
      Model was trained on transformed data, different to inputed data
**** Re-evaluated on data (using FilteredClassifier)
     Same summary, but no warnings.
** Replacing Missing Values
   Using j48 with cross-validation.
*** iris
**** Summary
     | Correctly Classified Instances   | 144 (96%) |
     | Incorrectly Classified Instances |    6 (4%) |
     | Kappa statistic                  |      0.94 |
     | Mean absolute error              |     0.035 |
     | Root mean squared error          |    0.1586 |
     | Relative absolute error          |   7.8705% |
     | Root relative squared error      |  33.6353% |
     | Total Number of Instances        |       150 |
**** Average accuracies
     | TP Rate   | 0.960 |
     | FP Rate   | 0.020 |
     | Precision | 0.960 |
     | Recall    | 0.960 |
     | F-Measure | 0.960 |
     | MCC       | 0.940 |
     | ROC Area  | 0.968 |
     | PRC Rate  | 0.924 |
*** iris2 without ReplaceMissingValues filter
**** Summary
     | Correctly Classified Instances   | 141 (94%) |
     | Incorrectly Classified Instances |    9 (6%) |
     | Kappa statistic                  |      0.91 |
     | Mean absolute error              |    0.0587 |
     | Root mean squared error          |    0.1894 |
     | Relative absolute error          |  13.2144% |
     | Root relative squared error      |  40.1747% |
     | Total Number of Instances        |       150 |
**** Average accuracies
     | TP Rate   | 0.940 |
     | FP Rate   | 0.030 |
     | Precision | 0.941 |
     | Recall    | 0.940 |
     | F-Measure | 0.940 |
     | MCC       | 0.911 |
     | ROC Area  | 0.958 |
     | PRC Rate  | 0.908 |
*** iris2 with ReplaceMissingValues filter
**** Summary
     | Correctly Classified Instances   | 141 (94%) |
     | Incorrectly Classified Instances |    9 (6%) |
     | Kappa statistic                  |      0.91 |
     | Mean absolute error              |    0.0512 |
     | Root mean squared error          |    0.1911 |
     | Relative absolute error          |  11.5245% |
     | Root relative squared error      |  40.5457% |
     | Total Number of Instances        |       150 |
**** Average accuracies
     | TP Rate   | 0.940 |
     | FP Rate   | 0.030 |
     | Precision | 0.941 |
     | Recall    | 0.940 |
     | F-Measure | 0.940 |
     | MCC       | 0.911 |
     | ROC Area  | 0.964 |
     | PRC Rate  | 0.921 |
*** iris3 with ReplaceMissingValues filter
**** Summary
     | Correctly Classified Instances   | 142 (94.6667%) |
     | Incorrectly Classified Instances |    8 (5.3333%) |
     | Kappa statistic                  |           0.92 |
     | Mean absolute error              |         0.0561 |
     | Root mean squared error          |         0.1842 |
     | Relative absolute error          |       12.6137% |
     | Root relative squared error      |       39.0773% |
     | Total Number of Instances        |            150 |
**** Average accuracies
     | TP Rate   | 0.947 |
     | FP Rate   | 0.027 |
     | Precision | 0.949 |
     | Recall    | 0.947 |
     | F-Measure | 0.947 |
     | MCC       | 0.921 |
     | ROC Area  | 0.956 |
     | PRC Rate  | 0.902 |
** Transforming Numeric Values
*** No transformations
**** j48
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.trees.J48 -C 0.25 -M 2
Relation:     iris
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

J48 pruned tree
------------------

petalwidth <= 0.6: Iris-setosa (50.0)
petalwidth > 0.6
|   petalwidth <= 1.7
|   |   petallength <= 4.9: Iris-versicolor (48.0/1.0)
|   |   petallength > 4.9
|   |   |   petalwidth <= 1.5: Iris-virginica (3.0)
|   |   |   petalwidth > 1.5: Iris-versicolor (3.0/1.0)
|   petalwidth > 1.7: Iris-virginica (46.0/1.0)

Number of Leaves  : 	5

Size of the tree : 	9


Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         144               96      %
Incorrectly Classified Instances         6                4      %
Kappa statistic                          0.94  
Mean absolute error                      0.035 
Root mean squared error                  0.1586
Relative absolute error                  7.8705 %
Root relative squared error             33.6353 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 0.980    0.000    1.000      0.980    0.990      0.985    0.990     0.987     Iris-setosa
                 0.940    0.030    0.940      0.940    0.940      0.910    0.952     0.880     Iris-versicolor
                 0.960    0.030    0.941      0.960    0.950      0.925    0.961     0.905     Iris-virginica
Weighted Avg.    0.960    0.020    0.960      0.960    0.960      0.940    0.968     0.924     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 49  1  0 |  a = Iris-setosa
  0 47  3 |  b = Iris-versicolor
  0  2 48 |  c = Iris-virginica
#+END_SRC
**** IBk
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.lazy.IBk -K 1 -W 0 -A "weka.core.neighboursearch.LinearNNSearch -A \"weka.core.EuclideanDistance -R first-last\""
Relation:     iris
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

IB1 instance-based classifier
using 1 nearest neighbour(s) for classification


Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         143               95.3333 %
Incorrectly Classified Instances         7                4.6667 %
Kappa statistic                          0.93  
Mean absolute error                      0.0399
Root mean squared error                  0.1747
Relative absolute error                  8.9763 %
Root relative squared error             37.0695 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 1.000    0.000    1.000      1.000    1.000      1.000    1.000     1.000     Iris-setosa
                 0.940    0.040    0.922      0.940    0.931      0.896    0.952     0.887     Iris-versicolor
                 0.920    0.030    0.939      0.920    0.929      0.895    0.947     0.894     Iris-virginica
Weighted Avg.    0.953    0.023    0.953      0.953    0.953      0.930    0.966     0.927     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 50  0  0 |  a = Iris-setosa
  0 47  3 |  b = Iris-versicolor
  0  4 46 |  c = Iris-virginica
#+END_SRC
**** Naive-Bayes
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.bayes.NaiveBayes 
Relation:     iris
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

Naive Bayes Classifier

                         Class
Attribute          Iris-setosa Iris-versicolor  Iris-virginica
                        (0.33)          (0.33)          (0.33)
===============================================================
sepallength
  mean                   4.9913          5.9379          6.5795
  std. dev.               0.355          0.5042          0.6353
  weight sum                 50              50              50
  precision              0.1059          0.1059          0.1059

sepalwidth
  mean                   3.4015          2.7687          2.9629
  std. dev.              0.3925          0.3038          0.3088
  weight sum                 50              50              50
  precision              0.1091          0.1091          0.1091

petallength
  mean                   1.4694          4.2452          5.5516
  std. dev.              0.1782          0.4712          0.5529
  weight sum                 50              50              50
  precision              0.1405          0.1405          0.1405

petalwidth
  mean                   0.2743          1.3097          2.0343
  std. dev.              0.1096          0.1915          0.2646
  weight sum                 50              50              50
  precision              0.1143          0.1143          0.1143



Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         144               96      %
Incorrectly Classified Instances         6                4      %
Kappa statistic                          0.94  
Mean absolute error                      0.0342
Root mean squared error                  0.155 
Relative absolute error                  7.6997 %
Root relative squared error             32.8794 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 1.000    0.000    1.000      1.000    1.000      1.000    1.000     1.000     Iris-setosa
                 0.960    0.040    0.923      0.960    0.941      0.911    0.992     0.983     Iris-versicolor
                 0.920    0.020    0.958      0.920    0.939      0.910    0.992     0.986     Iris-virginica
Weighted Avg.    0.960    0.020    0.960      0.960    0.960      0.940    0.994     0.989     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 50  0  0 |  a = Iris-setosa
  0 48  2 |  b = Iris-versicolor
  0  4 46 |  c = Iris-virginica


#+END_SRC
*** Standardised
**** j48
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.trees.J48 -C 0.25 -M 2
Relation:     iris-weka.filters.unsupervised.attribute.Standardize
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

J48 pruned tree
------------------

petalwidth <= -0.784457: Iris-setosa (50.0)
petalwidth > -0.784457
|   petalwidth <= 0.656917
|   |   petallength <= 0.64686: Iris-versicolor (48.0/1.0)
|   |   petallength > 0.64686
|   |   |   petalwidth <= 0.394849: Iris-virginica (3.0)
|   |   |   petalwidth > 0.394849: Iris-versicolor (3.0/1.0)
|   petalwidth > 0.656917: Iris-virginica (46.0/1.0)

Number of Leaves  : 	5

Size of the tree : 	9


Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         144               96      %
Incorrectly Classified Instances         6                4      %
Kappa statistic                          0.94  
Mean absolute error                      0.035 
Root mean squared error                  0.1586
Relative absolute error                  7.8705 %
Root relative squared error             33.6353 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 0.980    0.000    1.000      0.980    0.990      0.985    0.990     0.987     Iris-setosa
                 0.940    0.030    0.940      0.940    0.940      0.910    0.952     0.880     Iris-versicolor
                 0.960    0.030    0.941      0.960    0.950      0.925    0.961     0.905     Iris-virginica
Weighted Avg.    0.960    0.020    0.960      0.960    0.960      0.940    0.968     0.924     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 49  1  0 |  a = Iris-setosa
  0 47  3 |  b = Iris-versicolor
  0  2 48 |  c = Iris-virginica
#+END_SRC
**** IBk
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.lazy.IBk -K 1 -W 0 -A "weka.core.neighboursearch.LinearNNSearch -A \"weka.core.EuclideanDistance -R first-last\""
Relation:     iris-weka.filters.unsupervised.attribute.Standardize
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

IB1 instance-based classifier
using 1 nearest neighbour(s) for classification


Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         143               95.3333 %
Incorrectly Classified Instances         7                4.6667 %
Kappa statistic                          0.93  
Mean absolute error                      0.0399
Root mean squared error                  0.1747
Relative absolute error                  8.9763 %
Root relative squared error             37.0695 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 1.000    0.000    1.000      1.000    1.000      1.000    1.000     1.000     Iris-setosa
                 0.940    0.040    0.922      0.940    0.931      0.896    0.952     0.887     Iris-versicolor
                 0.920    0.030    0.939      0.920    0.929      0.895    0.947     0.894     Iris-virginica
Weighted Avg.    0.953    0.023    0.953      0.953    0.953      0.930    0.966     0.927     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 50  0  0 |  a = Iris-setosa
  0 47  3 |  b = Iris-versicolor
  0  4 46 |  c = Iris-virginica
#+END_SRC
**** Naive-Bayes
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.bayes.NaiveBayes 
Relation:     iris-weka.filters.unsupervised.attribute.Standardize
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

Naive Bayes Classifier

                         Class
Attribute          Iris-setosa Iris-versicolor  Iris-virginica
                        (0.33)          (0.33)          (0.33)
===============================================================
sepallength
  mean                  -1.0153          0.1125          0.8951
  std. dev.              0.4462          0.6017          0.7736
  weight sum                 50              50              50
  precision              0.1279          0.1279          0.1279

sepalwidth
  mean                   0.8353         -0.6189          -0.151
  std. dev.              0.8837          0.7296          0.7169
  weight sum                 50              50              50
  precision              0.2516          0.2516          0.2516

petallength
  mean                  -1.3057          0.2866          1.0207
  std. dev.              0.1092          0.2621          0.3103
  weight sum                 50              50              50
  precision              0.0796          0.0796          0.0796

petalwidth
  mean                  -1.2819          0.1827          1.0902
  std. dev.              0.1589          0.2814          0.3705
  weight sum                 50              50              50
  precision              0.1498          0.1498          0.1498



Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         140               93.3333 %
Incorrectly Classified Instances        10                6.6667 %
Kappa statistic                          0.9   
Mean absolute error                      0.0445
Root mean squared error                  0.1629
Relative absolute error                 10.0045 %
Root relative squared error             34.5564 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 1.000    0.000    1.000      1.000    1.000      1.000    1.000     1.000     Iris-setosa
                 0.900    0.050    0.900      0.900    0.900      0.850    0.988     0.974     Iris-versicolor
                 0.900    0.050    0.900      0.900    0.900      0.850    0.988     0.980     Iris-virginica
Weighted Avg.    0.933    0.033    0.933      0.933    0.933      0.900    0.992     0.985     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 50  0  0 |  a = Iris-setosa
  0 45  5 |  b = Iris-versicolor
  0  5 45 |  c = Iris-virginica


#+END_SRC
*** Normalised
**** j48
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.trees.J48 -C 0.25 -M 2
Relation:     iris-weka.filters.unsupervised.attribute.Normalize-S1.0-T0.0
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

J48 pruned tree
------------------

petalwidth <= 0.208333: Iris-setosa (50.0)
petalwidth > 0.208333
|   petalwidth <= 0.666667
|   |   petallength <= 0.661017: Iris-versicolor (48.0/1.0)
|   |   petallength > 0.661017
|   |   |   petalwidth <= 0.583333: Iris-virginica (3.0)
|   |   |   petalwidth > 0.583333: Iris-versicolor (3.0/1.0)
|   petalwidth > 0.666667: Iris-virginica (46.0/1.0)

Number of Leaves  : 	5

Size of the tree : 	9


Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         144               96      %
Incorrectly Classified Instances         6                4      %
Kappa statistic                          0.94  
Mean absolute error                      0.035 
Root mean squared error                  0.1586
Relative absolute error                  7.8705 %
Root relative squared error             33.6353 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 0.980    0.000    1.000      0.980    0.990      0.985    0.990     0.987     Iris-setosa
                 0.940    0.030    0.940      0.940    0.940      0.910    0.952     0.880     Iris-versicolor
                 0.960    0.030    0.941      0.960    0.950      0.925    0.961     0.905     Iris-virginica
Weighted Avg.    0.960    0.020    0.960      0.960    0.960      0.940    0.968     0.924     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 49  1  0 |  a = Iris-setosa
  0 47  3 |  b = Iris-versicolor
  0  2 48 |  c = Iris-virginica
#+END_SRC
**** IBk
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.lazy.IBk -K 1 -W 0 -A "weka.core.neighboursearch.LinearNNSearch -A \"weka.core.EuclideanDistance -R first-last\""
Relation:     iris-weka.filters.unsupervised.attribute.Normalize-S1.0-T0.0
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

IB1 instance-based classifier
using 1 nearest neighbour(s) for classification


Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         143               95.3333 %
Incorrectly Classified Instances         7                4.6667 %
Kappa statistic                          0.93
Mean absolute error                      0.0399
Root mean squared error                  0.1747
Relative absolute error                  8.9763 %
Root relative squared error             37.0695 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 1.000    0.000    1.000      1.000    1.000      1.000    1.000     1.000     Iris-setosa
                 0.940    0.040    0.922      0.940    0.931      0.896    0.952     0.887     Iris-versicolor
                 0.920    0.030    0.939      0.920    0.929      0.895    0.947     0.894     Iris-virginica
Weighted Avg.    0.953    0.023    0.953      0.953    0.953      0.930    0.966     0.927     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 50  0  0 |  a = Iris-setosa
  0 47  3 |  b = Iris-versicolor
  0  4 46 |  c = Iris-virginica
#+END_SRC
**** Naive-Bayes
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.bayes.NaiveBayes 
Relation:     iris-weka.filters.unsupervised.attribute.Normalize-S1.0-T0.0
Instances:    150
Attributes:   5
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

Naive Bayes Classifier

                         Class
Attribute          Iris-setosa Iris-versicolor  Iris-virginica
                        (0.33)          (0.33)          (0.33)
===============================================================
sepallength
  mean                   0.2012          0.4541          0.6371
  std. dev.              0.0938          0.1441          0.1738
  weight sum                 50              50              50
  precision              0.0294          0.0294          0.0294

sepalwidth
  mean                   0.5909          0.3191          0.4018
  std. dev.              0.1559          0.1241          0.1312
  weight sum                 50              50              50
  precision              0.0455          0.0455          0.0455

petallength
  mean                   0.0805          0.5514           0.771
  std. dev.              0.0293           0.079           0.094
  weight sum                 50              50              50
  precision              0.0238          0.0238          0.0238

petalwidth
  mean                   0.0676          0.5029          0.8057
  std. dev.              0.0477          0.0769          0.1118
  weight sum                 50              50              50
  precision              0.0476          0.0476          0.0476



Time taken to build model: 0 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         142               94.6667 %
Incorrectly Classified Instances         8                5.3333 %
Kappa statistic                          0.92  
Mean absolute error                      0.0361
Root mean squared error                  0.1593
Relative absolute error                  8.1248 %
Root relative squared error             33.8031 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 1.000    0.000    1.000      1.000    1.000      1.000    1.000     1.000     Iris-setosa
                 0.920    0.040    0.920      0.920    0.920      0.880    0.991     0.982     Iris-versicolor
                 0.920    0.040    0.920      0.920    0.920      0.880    0.991     0.985     Iris-virginica
Weighted Avg.    0.947    0.027    0.947      0.947    0.947      0.920    0.994     0.989     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 50  0  0 |  a = Iris-setosa
  0 46  4 |  b = Iris-versicolor
  0  4 46 |  c = Iris-virginica


#+END_SRC
*** TODO Why is Naive-Bayes dependent on the filters?
** DONE Discretisation
   CLOSED: [2020-02-13 Thu 12:07]
   Making numerical sets into categories (bins)
   https://weka.sourceforge.io/doc.dev/weka/filters/unsupervised/attribute/Discretize.html
*** More bins allows produced tree to make more decisions.
** TODO Creating New Attributes
#+BEGIN_SRC text
=== Run information ===

Scheme:       weka.classifiers.trees.J48 -C 0.25 -M 2
Relation:     iris-weka.filters.unsupervised.attribute.AddExpression-Ea1 + a2 + a3 + a4-NDimSum-weka.filters.unsupervised.attribute.AddExpression-Ea3 * a4-NApproxPetalArea
Instances:    150
Attributes:   7
              sepallength
              sepalwidth
              petallength
              petalwidth
              class
              DimSum
              ApproxPetalArea
Test mode:    10-fold cross-validation

=== Classifier model (full training set) ===

J48 pruned tree
------------------

petalwidth <= 0.6: Iris-setosa (50.0)
petalwidth > 0.6
|   ApproxPetalArea <= 7.35: Iris-versicolor (46.0)
|   ApproxPetalArea > 7.35
|   |   ApproxPetalArea <= 8.64
|   |   |   DimSum <= 15.8: Iris-virginica (8.0/2.0)
|   |   |   DimSum > 15.8: Iris-versicolor (2.0)
|   |   ApproxPetalArea > 8.64: Iris-virginica (44.0)

Number of Leaves  : 	5

Size of the tree : 	9


Time taken to build model: 0.02 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances         140               93.3333 %
Incorrectly Classified Instances        10                6.6667 %
Kappa statistic                          0.9   
Mean absolute error                      0.044 
Root mean squared error                  0.1956
Relative absolute error                  9.8919 %
Root relative squared error             41.5013 %
Total Number of Instances              150     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 0.980    0.000    1.000      0.980    0.990      0.985    0.990     0.987     Iris-setosa
                 0.920    0.060    0.885      0.920    0.902      0.852    0.974     0.913     Iris-versicolor
                 0.900    0.040    0.918      0.900    0.909      0.864    0.965     0.949     Iris-virginica
Weighted Avg.    0.933    0.033    0.934      0.933    0.934      0.900    0.976     0.949     

=== Confusion Matrix ===

  a  b  c   <-- classified as
 49  1  0 |  a = Iris-setosa
  0 46  4 |  b = Iris-versicolor
  0  5 45 |  c = Iris-virginica

#+END_SRC
   
* Notes
** Remove arguements
   Need to use column no. of attribute, not name.
** Weka's "Detailed Accuracy by Class" outputs
   From https://stackoverflow.com/questions/2903933/how-to-interpret-weka-classification
*** TP Rate
    Rate of true positives (instances correctly classified as a given class)
*** FP Rate
    Rate of false positives (instances falsely classified as a given class)
*** Precision
    Proportion of instances that are truly of a class divided by the total instances classified as that class
*** Recall
    Proportion of instances classified as a given class divided by the actual total in that class (equivalent to TP rate)
*** F-Measure
    A combined measure for precision and recall calculated as 2 * Precision * Recall / (Precision + Recall)
*** TODO MCC
*** TODO ROC Area
*** TODO PRC Rate
** ReplaceMissingValues
   Replaces all missing values for nominal and numeric attributes in a dataset with the modes and means from the training data. 
*** In the irs data
    Missing values were all replaced with the mean from the set of existing values.
** kNN
   k-nearest neighbours algorithm
